name: CD
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Create PEM file
        run: |
          echo "${{ secrets.BASE64_KEY }}" | base64 --decode > key.pem
          chmod 600 key.pem
    
      - name: Debug
        run: |
          ls
      - name: Pull then rebuild the app
        timeout-minutes: 10
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key_path: key.pem
          port: 22
          command_timeout: 600s
          script: |
            cd ujk-bnsp
            git pull
            sudo docker stop go-app-container || true
            sudo docker rm go-app-container || true
            sudo docker build -t go-app .
            sudo docker run --name go-app-container -d -p 80:5500 go-app
            

